name: "Add ruleset"
on: push

jobs:
  add_ruleset:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Add ruleset
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/rulesets \
          -f "name=super cool ruleset" -f "target=branch" -f "enforcement=active" \
          -f "ref_name[include[]]=refs/heads/main" \
          -f "ref_name[include[]]=refs/heads/master" -f "ref_name[exclude[]]=refs/heads/dev*" \
          -f "rules[][type]=commit_author_email_pattern" -f "rules[][parameters][operator]=contains" \
          -f "rules[][parameters][pattern]=github"
          echo '/repos/${{ github.repository_owner }}/${{ github.repository }}/rulesets'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
